spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      routes:
        - id: hello-api #Fill in real names when they're determined
          uri: http://hello-api:8080
          predicates:
            - Path=/api/hello/**
        - id: usage-service
          uri: http://usage-service:8080
          predicates:
            - Path=/usage/**
        - id: anotherService
          uri: http://another-service:8080
          predicates:
            - Path=/another-service/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak/realms/example-realm
server:
  port: 8080
