spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://mysql:3306/user_db
    username: user_user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081
