spring:
  application:
    name: billing-service
  datasource:
    url: jdbc:mysql://localhost:3306/billing_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: billing-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
    properties:
      spring.json.trusted.packages: com.ratelimit.billing.kafka,com.ratelimit.usage.kafka,com.ratelimit.dunning.dto
      spring.json.value.default.type: com.ratelimit.billing.kafka.UsageAggregateBillingMessage
      spring.json.use.type.headers: false

server:
  port: 8084
