spring:
  application:
    name: dunning-service
  datasource:
    url: jdbc:postgresql://localhost:5432/dunning_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8085
