spring:
  application:
    name: usage-service
  datasource:
    url: jdbc:mysql://mysql:3306/usage_db
    username: usage_user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
    consumer:
      group-id: usage-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: "com.ratelimit.subscription.dto"
        spring.json.use.type.headers: true
  data:
    redis:
      host: redis
      port: 6379

server:
  port: 8083

logging:
  level:
    root: INFO
    com.ratelimit: DEBUG

jakarta:
  persistence:
    jdbc:
      url: jdbc:mysql://mysql:3306/usage_db
      user: usage_user
      password: password