spring:
  application:
    name: usage-service
  datasource:
    url: jdbc:mysql://mysql:3306/usage_db
    username: usage_user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

server:
  port: 8083
